import React from "react";
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import BaseLayout from "@/layouts/BaseLayout";

export async function getStaticProps({ locale }: { locale: string }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, [
                'default',
                'menu',
            ])),
        },
    }
}

export default function Home() {
    const { t } = useTranslation()

    return (
        <BaseLayout>
            <Head>
                <title>next-i18next demo</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <h2 className="mb-3 text-3xl font-extrabold tracking-tight text-gray-900">{t('title')}</h2>
                <p className="mb-3 text-gray-500">{t('description')}</p>
            </div>
        </BaseLayout>
    )
}
